spring.application.name=SpaceBack

# Credentials
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Drop and recreate db at each runtime
spring.jpa.hibernate.ddl-auto=create

# SQL statement logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logging
logging.level.root=INFO
