spring.application.name=SpaceBack

# Credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=sa

# Drop and recreate db at each runtime
spring.jpa.hibernate.ddl-auto=create

# Db initialization with data
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# SQL statement logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logging
logging.level.root=INFO
